### ISSUE TITLE
Flexible Custom Job Support for OpenForms Helm Chart

### ISSUE THREAD

**Issue by Tiho0135** [maykinmedia/charts#235]
# Feature Request: Flexible Custom Job Support for OpenForms Helm Chart

## Background

Currently, our OpenForms Helm chart does **not** provide a straightforward way to run custom one-off scripts as a Kubernetes Job. This limitation makes it difficult to automate post-deployment fixes, data migrations, or other remedial actions that may be required after deploying or upgrading OpenForms—especially when issues are discovered in production or staging environments.

This need was highlighted by a customer who requested a way to automate such tasks as part of their deployment pipeline, to ensure smoother and more reliable rollouts of new releases.

## Problem

- There is **no built-in job container** or mechanism in the chart to run arbitrary Python or Django scripts.
- Manual intervention is often required to fix issues or perform post-deployment steps, which is error-prone and not scalable.
- We want to empower operators to automate these tasks, making deployments more robust and less dependent on manual fixes.

## Real-World Example

From the [Open Forms changelog](https://open-forms.readthedocs.io/en/latest/changelog.html):

> **Manual intervention required**
>
> In the 3.1.1 bugfix release we fixed a bug regarding the default values of some components being `null`. We added a script to fix any forms that still might be affected by these issues. You should run this script after deploying the patch release, to make sure the default values of affected components are fixed.
>
> **Script to run:**
> ```
> python /app/bin/fix_component_default_values.py
> ```

Currently, running such a script requires manual execution via `kubectl exec` or similar, which is not ideal for automation or repeatability.

## Proposed Solution

Add a **flexible job template** to the Helm chart, configurable via `values.yaml`, that allows running custom scripts in three different ways:

### 1. **managepy** (default)
- Runs a Django management command (e.g., `python /app/src/manage.py runscript --script /app/scripts/my_script.py`)
- Both the command and script path are configurable.

### 2. **python**
- Runs a Python script directly (e.g., `python /app/scripts/my_script.py`)
- The script can be supplied via a ConfigMap, Secret, or PVC.
- For convenience, the script content can also be provided directly in `values.yaml` and rendered into a ConfigMap.

### 3. **container**
- Runs a Python script that is already present in the container image (e.g., `python /app/bin/fix_component_default_values.py`)
- No volume mount is required; just specify the path in `values.yaml`.

### Example: Running a Script Already in the Image (as required by the changelog)

```yaml
tempjobdjango:
  enabled: true
  mode: "container"
  scriptPath: "/app/bin/fix_component_default_values.py"
```

### Example: Running a Django Management Command

```yaml
tempjobdjango:
  enabled: true
  mode: "managepy"
  command: "runscript"
  scriptPath: "/app/scripts/db_cleanup.py"
```

### Example: Running a Python Script Supplied via ConfigMap

```yaml
tempjobdjango:
  enabled: true
  mode: "python"
  scriptPath: "/app/scripts/fix_permissions.py"
  scriptContent: |
    #!/usr/bin/env python
    print("Automated fix for OpenForms deployment issues.")
  scriptFileName: "fix_permissions.py"
```

## Helm Template Logic

```jinja
args:
  - |
    # Modes:
    #   python    - run a script mounted via ConfigMap/Secret/PVC
    #   managepy  - run a Django management command, optionally with a script
    #   container - run a script already present in the container image
    {{- if eq .Values.tempjobdjango.mode "python" -}}
    python {{ .Values.tempjobdjango.scriptPath }}
    {{- else if eq .Values.tempjobdjango.mode "managepy" -}}
    python /app/src/manage.py{{ if .Values.tempjobdjango.command }} {{ .Values.tempjobdjango.command }}{{ end }}{{ if .Values.tempjobdjango.scriptPath }} --script {{ .Values.tempjobdjango.scriptPath }}{{ end }}
    {{- else if eq .Values.tempjobdjango.mode "container" -}}
    python {{ .Values.tempjobdjango.scriptPath }}
    {{- end -}}
```

## Benefits

- **Automates post-deployment fixes** and custom tasks, reducing manual intervention.
- **Flexible:** Supports all common ways to supply and execute scripts.
- **Configurable:** All options are controlled via `values.yaml`.
- **Customer-driven:** Directly addresses a customer request for more robust, automated deployments.
- **Aligns with upstream recommendations:** For example, the Open Forms team recommends running fix scripts after certain upgrades ([see changelog](https://open-forms.readthedocs.io/en/latest/changelog.html)).

---

**Action:**  
Please review and test the new job modes. This will help us automate and standardize post-deployment tasks for OpenForms, making our releases more reliable and customer-friendly.
